spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/taskservicedb
    username: root
    password: Mysql@.1234
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/     
server:
  port: 8083   
