spring:
  application:
    name: user-microservices
  datasource:
    url: jdbc:mysql://localhost:3306/userservicedb
    username: root
    password: Mysql@.1234
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/        
server:
  port: 8082
#task-service:
  #ribbon:
   # listOfServers: http://localhost:8083/,http://localhost:8085/